# -*- coding: utf-8 -*-
"""videoclub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yh1JHDrKAVGEHnX-vvIHgMzcQljY0G-o
"""

#revisar todas las funciones y agregar validaciones
#empezar a comerntar el codigo

import os


############################### FUNCIONES CONSULTAR PELICULA ############################

def consultar_estado_pelicula(codigo_de_barras): 
    with open("peliculas.txt", "r") as jArchi:
        with open("clientes.txt", "r") as xArchi:
            linea1 = jArchi.readline()
            linea2 = xArchi.readline()
            while linea1 != "" and linea2 != "":
                renglon1 = linea1.split(',')
                renglon2 = linea2.split(',')
                if codigo_de_barras == renglon1[0] and renglon1[3] == "Disponible":
                    jArchi.close()
                    print("Pelicula:", renglon1[1])
                    print("Estado: DISPONIBLE")
                    return "¡ESTA PELICULA SE PUEDE ALQUILAR!"
                elif codigo_de_barras == renglon2[5]:
                    xArchi.close()
                    print("Pelicula:", renglon1[1])
                    print("Estado: ALQUILADA")
                    print("DNI del Cliente:", renglon2[0])
                    print("Nombre y Apellido del Cliente:", renglon2[1])
                    return "¡ESTA PELICULA NO SE PUEDE ALQUILAR!"
                linea2 = xArchi.readline()
                linea1 = jArchi.readline()
            xArchi.close()
            jArchi.close()
            return "¡La Pelicula ingresada, no existe en la Base De Datos!"

######################## FUNCIONES GESTION DE CLIENTES #######################

# --------AGREGAR CLIENTE--------#

def agregar_cliente(documento, nombre, apellido, telefono, direccion):#creamos una funcion que se llamara "agregar cliente" y en las variables pondremos los datos del cliente
    with open("clientes.txt", "a") as jArchi:#creamos un with open para que pueda acceder a nuestro archivos txt, y le agregamos "a" para abrir el txt alojado en nuestra varible jarchi
        jArchi.write(documento + "," + (nombre.lower().capitalize()) + " " + (apellido.lower().capitalize()) + "," + telefono + "," + (direccion.lower().capitalize()) + "," + "Activo" + "," + "0" + "," + "\n") 
        jArchi.close()#cerramos el archivo en nuestra varible poniendo close
        return "¡Se agrego correctamente un Nuevo Cliente!"# creamos un return para que nos devuelva el mensaje indicando que la creacion fue existosa


# --------CONSUTAR CLIENTE--------#

def consultar_cliente(documento):#creamos una funcion que se llamara consultar_cliente y le agregaremos una variable que se llame documento
    with open("clientes.txt", "r") as jArchi:##creamos un with open para que pueda acceder a nuestro archivos txt, y le agregamos "r" para que pueda leer nuestro fichero
        linea = jArchi.readline()#creamos una varible que se llamara linea y almacenara otra varible que se llame jarchi y le agregamos readline para que pueda leer las lineas que se crea dentro de jarchi
        while linea != "":# creamos un bucle while dentro de la varible linea si es igual o diferente de las lineas
            renglon = linea.split(',')# creara un renglon seguido de un coma
            if documento == renglon[0]:#creamos otro bucle un if en la varible documento si es igual a renglon creara una linea
                jArchi.close()#cerramos el archivo en nuestra variable poniendo close
                return renglon[4]#creamos un return que nos devuelva 4 renglones nuevo
            linea = jArchi.readline()##creamos una variable que se llamara linea y almacenara otra varible que se llame jarchi y le agregamos readline para que pueda leer las lineas que se crea dentro de jarchi
        jArchi.close()#cerramos el archivo en nuestra variable poniendo close
        return "¡No existe el Cliente en la Base de Datos!"# creamos un return para que nos devuelva el mensaje indicando que el no existe el nombre del cliente en la Database


# --------MODIFICAR CLIENTE--------#

def modificar_cliente_telefono(documento, telefono):
    with open("clientes.txt", "r") as rArchi:
        with open("clientescpy.txt", "w") as wArchi:
            linea = rArchi.readline()
            while linea != "":
                renglon = linea.split(',')
                if documento == renglon[0]:
                    wArchi.writelines(renglon[0] + "," + renglon[1] + "," + telefono + "," + renglon[3] + "," + renglon[4] + "," + renglon[5] + "," + "\n")
                else:
                    wArchi.write(linea)
                linea = rArchi.readline()
            wArchi.close()
        rArchi.close()
    with open("clientescpy.txt", "r") as fcopia:
        with open("clientes.txt", "w") as foriginal:
            for registro in fcopia:
                foriginal.write(registro)
            fcopia.close()
        foriginal.close()
        return "¡Se modifico el Telefono correctamente!"

def modificar_cliente_direccion(direccion):
    with open("clientes.txt", "r") as rArchi:
        with open("clientescpy.txt", "w") as wArchi:
            linea = rArchi.readline()
            while linea != "":
                renglon = linea.split(',')
                if documento == renglon[0]:
                    wArchi.writelines(renglon[0] + "," + renglon[1] + "," + renglon[2] + "," + (direccion.lower().capitalize()) + "," + renglon[4] + "," +  renglon[5] + "," + "\n")
                else:
                    wArchi.write(linea)
                linea = rArchi.readline()
            wArchi.close()
        rArchi.close()
    with open("clientescpy.txt", "r") as fcopia:
        with open("clientes.txt", "w") as foriginal:
            for registro in fcopia:
                foriginal.write(registro)
            fcopia.close()
        foriginal.close()
        return "¡Se modifico la Direccion correctamente!"


# --------BORRAR CLIENTE--------#

def borrar_cliente(documento):#definimos una funcion y lo llamamos "borrar cliente" y creamos la variable "documento"
    with open("clientes.txt", "r") as rArchi:#creamos un with open para que abre nuestros archivos txt y y un "r" para que pueda leer nuestros archivos txt
        with open("clientescpy.txt", "w") as wArchi:#creamos un with open para que abre nuestros archivos txt y y un "w" para que pueda abrir nuestros archivos txt
            linea = rArchi.readline()#creamos una variable que se llamara linea y que almacenara la variable rarchi y luego un readline para que pueda leer las lineas que se genera
            while linea != "":#creamos un Bucle while en la variable linea si es distinto o igual a las comillas se creara un renglon
                renglon = linea.split(',')# se creara la variable renglon y a la variable linea se le creara un split esto permitira crear espacios en nuestros renglon
                if documento != renglon[0]:#se creara un if en la variables documento si es disnton o igual a ka variables renglon se genera un nuevo renglon
                    wArchi.write(linea)#y en la variables warchi se le asignara un write esto permitira leear el contenido de la variables linea 
                linea = rArchi.readline()#en la variables linea se leera rarchi y se leera la lineas generadas
            wArchi.close()#cerramos el archivos
        rArchi.close()##cerramos el archivos
    with open("clientescpy.txt", "r") as fcopia:#creamos un with open para que abre nuestros archivos txt y y un "r" para que pueda leer nuestros archivos txt
        with open("clientes.txt", "w") as foriginal:#creamos un with open para que abre nuestros archivos txt y y un "w" para que pueda abrir nuestros archivos txt
            for registro in fcopia:#creamos un for en el registro
                foriginal.write(registro)#se le asignara un write esto permitira leear el contenido de la variables foriginal que esta almacenado dentro de registro
            fcopia.close()#cerramos el archivo
        foriginal.close()#cerramos el archivo
        return "¡Se Elimino el Cliente correctamente!"

########################## FUNCIONES GESTION PELICULAS ####################

# --------ALTA PELICULA--------#

def agregar_pelicula(codigo_de_barra, nombre_pelicula, categoria):#definimos una funcion y lo llamamos "agregar pelicula" creamos 3 variables cod de barra,nombre de pelicula y su categoria
    with open("peliculas.txt", "a") as jArchi:#creamos un with open para que abre nuestros archivos txt y y un "a" para que pueda abrir nuestros archivos txt
        jArchi.write(codigo_de_barra + "," + (nombre_pelicula.lower().capitalize()) + "," + (categoria.lower().capitalize()) + "," + "Disponible" + "," + "0" + "," + "\n")#creamos la variable jarchi y un write para que abre las siguentes variables
        jArchi.close()#cerramos  nuestra variable con un close para cerrar el archivo
        return "¡Se agrego correctamente una Nueva Pelicula!"#creamos un return para que indique el mensaje de que se agrego correctamente la pelicula

# --------CONSULTAR PELICULA--------#

def consultar_pelicula(codigo_de_barras):
    with open("peliculas.txt", "r") as kArchi:
        linea = kArchi.readline()
        while linea != "":
            renglon = linea.split(',')
            if codigo_de_barras == renglon[0]:
                print()
                print("Codigo de Barras: ", renglon[0])
                print("Nombre: ", renglon[1])
                print("Categoria: ", renglon[2])
                print("Estado: ", renglon[3])
                print("Cliente: ", renglon[4])
                print()
                return "¡Pelicula Encontrada!"
            linea = kArchi.readline()
        kArchi.close()
        return "!No existe la Pelicula en la Base de Datos!"

# --------MODIFICAR PELICULA--------#

def modificar_pelicula(codigo_de_barras, nombre, categoria, estado, cliente):#Definimos una funcion y lo llamamos modificar_pelicula y creamos las  variables propias dicha de una pelicula
    with open("peliculas.txt", "r") as rArchi:#creamos un with open para que abre nuestros archivos txt y y un "r" para que pueda leer nuestros archivos txt
        with open("peliculascpy.txt", "w") as wArchi:#creamos un with open para que abre nuestros archivos txt y y un "w" para que pueda abrir nuestros archivos txt
            linea = rArchi.readline()#creamos la variables linea y lo almacenamos en rarchi.creamos un readline para que leea las lineas generadas
            while linea != "": #creamos un bucle while y si la variables linea es disitinto o igual creara una linea
                renglon = linea.split(',') #creamos la variables renglon y en la variables linea creamos un split que genera un espacio en los renglones
                if codigo_de_barras == renglon[0]:#creamos un if 
                    wArchi.writelines(codigo_de_barras + "," + (nombre.lower().capitalize()) + "," + (categoria.lower().capitalize()) + "," + (estado.lower().capitalize()) + "," + cliente + "," + "\n")
                else:
                    wArchi.write(linea)
                linea = rArchi.readline()
            wArchi.close()
        rArchi.close()
    with open("peliculascpy.txt", "r") as fcopia:
        with open("peliculas.txt", "w") as foriginal:
            for registro in fcopia:
                foriginal.write(registro)
            fcopia.close()
        foriginal.close()
        return "¡Se modificaron todos los Datos correctamente!"

# --------BORRAR PELICULA--------#

def borrar_pelicula(codigo_de_barra):
    with open("peliculas.txt", "r") as rArchi:
        with open("peliculascpy.txt", "w") as wArchi:
            linea = rArchi.readline()
            while linea != "":
                renglon = linea.split(',')
                if codigo_de_barra != renglon[0]:
                    wArchi.write(linea)
                linea = rArchi.readline()
            wArchi.close()
        rArchi.close()
    with open("peliculascpy.txt", "r") as fcopia:
        with open("peliculas.txt", "w") as foriginal:
            for registro in fcopia:
                foriginal.write(registro)
            fcopia.close()
        foriginal.close()
        return '\033[1m' + "¡Se Elimino la Pelicula correctamente!" + '\033[0m'

######################### FUNCIONES PRESTAMO DE PELICULA ####################

# --------REGISTRAR ALQUILER--------#

def registrar_alquiler_dni(codigo_de_barras, documento):
    with open("peliculas.txt", "r") as rArchi:
        with open("peliculascpy.txt", "w") as wArchi:
            linea = rArchi.readline()
            while linea != "":
                renglon = linea.split(',')
                if codigo_de_barras == renglon[0]:
                    wArchi.writelines(renglon[0] + "," + renglon[1] + "," + renglon[2] + "," + "Alquilada" + "," + documento + "," + "\n")
                else:
                    wArchi.write(linea)
                linea = rArchi.readline()
            wArchi.close()
        rArchi.close()
    with open("peliculascpy.txt", "r") as fcopia:
        with open("peliculas.txt", "w") as foriginal:
            for registro in fcopia:
                foriginal.write(registro)
            fcopia.close()
        foriginal.close()
        print("La Pelicula Codigo de Barras:", codigo_de_barras)
        return "Se registro al Cliente DNI:"

def registrar_alquiler_codigo(codigo_de_barras, documento):
    with open("clientes.txt", "r") as rArchi:
        with open("clientescpy.txt", "w") as wArchi:
            linea = rArchi.readline()
            while linea != "":
                renglon = linea.split(',')
                if documento == renglon[0]:
                    wArchi.writelines(renglon[0] + "," + renglon[1] + "," + renglon[2] + "," + renglon[3] + "," + renglon[4] + "," + codigo_de_barras + "," + "\n")
                else:
                    wArchi.write(linea)
                linea = rArchi.readline()
            wArchi.close()
        rArchi.close()
    with open("clientescpy.txt", "r") as fcopia:
        with open("clientes.txt", "w") as foriginal:
            for registro in fcopia:
                foriginal.write(registro)
            fcopia.close()
        foriginal.close()
        return documento

# --------REGISTRAR DEVOLUCION--------#

def registrar_devolucion_dni(codigo_de_barras, documento):
    with open("peliculas.txt", "r") as rArchi:
        with open("peliculascpy.txt", "w") as wArchi:
            linea = rArchi.readline()
            while linea != "":
                renglon = linea.split(',')
                if codigo_de_barras == renglon[0]:
                    wArchi.writelines(renglon[0] + "," + renglon[1] + "," + renglon[2] + "," + "Disponible" + "," + "0" + "," + "\n")
                else:
                    wArchi.write(linea)
                linea = rArchi.readline()
            wArchi.close()
        rArchi.close()
    with open("peliculascpy.txt", "r") as fcopia:
        with open("peliculas.txt", "w") as foriginal:
            for registro in fcopia:
                foriginal.write(registro)
            fcopia.close()
        foriginal.close()
        print("El Cliente DNI:", documento)
        return "Ya no tiene Alquilada la Pelicula, Codigo de Barras:"

def registrar_devolucion_codigo(codigo_de_barras, documento):
    with open("clientes.txt", "r") as rArchi:
        with open("clientescpy.txt", "w") as wArchi:
            linea = rArchi.readline()
            while linea != "":
                renglon = linea.split(',')
                if documento == renglon[0]:
                    wArchi.writelines(renglon[0] + "," + renglon[1] + "," + renglon[2] + "," + renglon[3] + "," + renglon[4] + "," + "0" + "," + "\n")
                else:
                    wArchi.write(linea)
                linea = rArchi.readline()
            wArchi.close()
        rArchi.close()
    with open("clientescpy.txt", "r") as fcopia:
        with open("clientes.txt", "w") as foriginal:
            for registro in fcopia:
                foriginal.write(registro)
            fcopia.close()
        foriginal.close()
        return codigo_de_barras

# --------PELICULAS DISPONIBLES--------#

def consultar_peliculas_disponibles():
    with open("peliculas.txt", "r") as kArchi:
        print("************************************** PELICULAS DISPONIBLES **************************************")
        print("{:^20}{:^1}{:^20}{:^1}{:^20}{:^1}{:^20}{:^1}{:^20}".format("CODIGO DE BARRAS", "|", "NOMBRE", "|", "CATEGORIA", "|", "ESTADO", "|", "CLIENTE"))
        linea = kArchi.readline()
        estado = "Disponible"
        while linea != "":
            renglon = linea.split(',')
            if estado == renglon[3]:
                print("{:^20}{:^1}{:^20}{:^1}{:^20}{:^1}{:^20}{:^1}{:^20}".format(renglon[0], "|", renglon[1], "|", renglon[2], "|", renglon[3], "|", renglon[4]))
            linea = kArchi.readline()
        print("----------------------------------------------------------------------------------------------------")
        kArchi.close()

###############################################################################
def limpioPantalla():
    sisOper = os.name
    if sisOper == "posix":  # si fuera UNIX, mac para Apple, java para maquina virtual Java
        os.system("clear")
    elif sisOper == "ce" or sisOper == "nt" or sisOper == "dos":  # windows
        os.system("cls")


########################################################################################

def muestroMenu():
    print("****************** VIDEO CLUB *******************")
    print('''
    0 - Consultar Disponibilidad Pelicula
    1 - Gestion de Clientes
    2 - Gestion de Peliculas
    3 - Prestamo de Pelicula
    4 - Limpiar pantalla
    5 - Salir
***************************************************
    ''')


def SubMenu_Prestamo_Pelicula():
    print('''
    0 - Consultar Peliculas Disponibles
    1 - Registrar Alquiler
    2 - Registrar Devolucion
    ''')


def SubMenu_Gestion_Clientes():
    print('''
    0 - Alta de Cliente
    1 - Consultar Estado de Cliente
    2 - Modificar Telefono o Direccion de Cliente
    3 - Eliminar Cliente
        ''')


def SubMenu_Gestion_Peliculas():
    print('''
    0 - Alta de Pelicula
    1 - Consultar Pelicula
    2 - Modificar Pelicula
    3 - Eliminar Pelicula
        ''')

def SubMenu_Modificar_Cliente():
    print('''
    0 - Modificar Telefono
    1 - Modificar Direccion
        ''')
#
opc = 0
while opc != 8:
    muestroMenu()  # Menu Principal
    opcion = int(input('\033[1m' + "Elija la opción deseada: " + '\033[0m'))
    if opcion == 0:
        print('\033[1m' + "¿Que pelicula desea buscar?" + '\033[0m')
        codigo_de_barras = input("Ingrese el Codigo de Barras: ")
        print(consultar_estado_pelicula(codigo_de_barras))
    elif opcion == 1:  # SubMenu Gestion de Clientes
        SubMenu_Gestion_Clientes()  # SubMenu Gestion de Clientes
        opcion = int(input('\033[1m' + "Elija la opción deseada: " + '\033[0m'))
        if opcion == 0:  # Alta Nuevo Cliente
            print('\033[1m' + "¡Se dara de Alta un Nuevo Cliente!" + '\033[0m')
            documento = input("Ingrese el DNI: ")
            nombre = input("Ingrese el Nombre: ")
            apellido = input("Ingrese el Apellido: ")
            telefono = input("Ingrese el Teléfono: ")
            direccion = input("Ingrese la Direccion: ")
            print(agregar_cliente(documento, nombre, apellido, telefono, direccion))
        elif opcion == 1:  # Consutar Estado Cliente
            print('\033[1m' + "¿Que Cliente desea buscar?" + '\033[0m')
            nombre = input("Ingrese el DNI: ")
            print("Estado: ", consultar_cliente(nombre))
        elif opcion == 2:  # Modificar Datos Cliente
            SubMenu_Modificar_Cliente()  # SubMenu Modificar Cliente
            opcion = int(input('\033[1m' + "Elija la opción deseada: " + '\033[0m'))
            if opcion == 0:
                print('\033[1m' + "¡Se modificará el Teléfono del Cliente!" + '\033[0m')
                documento = input("Ingrese el DNI: ")
                telefono = input("Ingrese el Nuevo Telefono: ")
                print(modificar_cliente_telefono(documento, telefono))
            elif opcion == 1:
                print('\033[1m' + "Se modificará la direccion del cliente." + '\033[0m')
                documento = input("Ingrese el DNI: ")
                direccion = input("Ingrese la Nueva Direccion: ")
                print(modificar_cliente_direccion(direccion))
        elif opcion == 3:  # Eliminar Cliente
            print('\033[1m' + "¡Se Eliminará un Cliente!" + '\033[0m')
            documento = input("Ingrese el DNI: ")
            print(borrar_cliente(documento))
    elif opcion == 2:  # SubMenu Gestion de Peliculas
        SubMenu_Gestion_Peliculas()  # SubMenu Gestion de Peliclas
        opcion = int(input('\033[1m' + "Elija la opción deseada: " + '\033[0m'))
        if opcion == 0:  # Alta de Pelicula
            print('\033[1m' + "¡Se dara de Alta una Nueva Pelicula!" + '\033[0m')
            codigo_de_barras = input("Ingrese el Codigo de Barras: ")
            nombre_pelicula = input("Ingrese el Nombre: ")
            categoria = input("Ingrese la Categoria: ")
            print(agregar_pelicula(codigo_de_barras, nombre_pelicula, categoria))
        elif opcion == 1:  # Consultar Pelicula
            print('\033[1m' + "¿Que Pelicula desea buscar?" + '\033[0m')
            codigo_de_barras = input("Ingrese el Codigo de Barras: ")
            print(consultar_pelicula(codigo_de_barras))
        elif opcion == 2:  # Modificar Datos Pelicula
            print('\033[1m' + "¡Se modificarán todos los Datos de la Pelicula!" + '\033[0m')
            print()
            codigo_de_barras = input("Ingrese el Codigo de Barras: ")
            nombre = input("Ingrese el Nombre: ")
            categoria = input("Ingrese la Categoria: ")
            estado = input("Ingrese el Estado: ")
            cliente = input("Ingrese DNI del Cliente: ")
            print()
            print(modificar_pelicula(codigo_de_barras, nombre, categoria, estado, cliente))
        elif opcion == 3:  # Eliminar Peliculas
            print('\033[1m' + "¡Se eliminará una Pelicula!" + '\033[0m')
            print()
            codigo_de_barras = input("Ingrese el Codigo de Barras: ")
            print()
            print(borrar_pelicula(codigo_de_barras))
    elif opcion == 3:  # Menu Prestamo Pelicula
        SubMenu_Prestamo_Pelicula()  # SubMenu Prestamo Pelicula
        opcion = int(input("Elija la opción deseada:"))
        if opcion == 0: #Peliculas Disponibles
            print("Las Peliculas Disponibles son:", consultar_peliculas_disponibles())
        elif opcion == 1: #Alquilar Pelicula
            print("¿Que pelicula desea alquilar?")
            codigo_de_barras = input("Ingrese el Codigo de Barras: ")
            print("¿A que Cliente?")
            documento = input("Ingrese el DNI: ")
            print(registrar_alquiler_dni(codigo_de_barras,documento), registrar_alquiler_codigo(codigo_de_barras,documento))
        elif opcion == 2: #Devolver Pelicula
            print("¿Que pelicula desea devolver?")
            codigo_de_barras = input("Ingrese el Codigo de Barras: ")
            documento = input("Ingrese el DNI: ")
            print(registrar_devolucion_dni(codigo_de_barras,documento), registrar_devolucion_codigo(codigo_de_barras,documento))
    elif opcion == 4:
        limpioPantalla()
    else:
        opc = opcion